class Deck
  [
  	{name: "aceOfSpades", face: "ace", suit: "spades"},
  	{name: "aceOfDiamonds", face: "ace", suit: "diamonds"},
  	{name: "aceOfClubs", face: "ace", suit: "clubs"},
  	{name: "aceOfHearts", face: "ace", suit: "hearts"},
  	{name: "twoOfSpades", face: "two", suit: "spades"},
  	{name: "twoOfDiamonds", face: "two", suit: "diamonds"},
  	{name: "twoOfClubs", face: "two", suit: "clubs"},
  	{name: "twoOfHearts", face: "two", suit: "hearts"},
  	{name: "threeOfSpades", face: "three", suit: "spades"},
  	{name: "threeOfDiamonds", face: "three", suit: "diamonds"},
  	{name: "threeOfClubs", face: "three", suit: "clubs"},
  	{name: "threeOfHearts", face: "three", suit: "hearts"},
  	{name: "fourOfSpades", face: "four", suit: "spades"},
  	{name: "fourOfDiamonds", face: "four", suit: "diamonds"},
  	{name: "fourOfClubs", face: "four", suit: "clubs"},
  	{name: "fourOfHearts", face: "four", suit: "hearts"},
  	{name: "fiveOfSpades", face: "five", suit: "spades"},
  	{name: "fiveOfDiamonds", face: "five", suit: "diamonds"},
  	{name: "fiveOfClubs", face: "five", suit: "clubs"},
  	{name: "fiveOfHearts", face: "five", suit: "hearts"},
  	{name: "sixOfSpades", face: "six", suit: "spades"},
  	{name: "sixOfDiamonds", face: "six", suit: "diamonds"},
  	{name: "sixOfClubs", face: "six", suit: "clubs"},
  	{name: "sixOfHearts", face: "six", suit: "hearts"},
  	{name: "sevenOfSpades", face: "seven", suit: "spades"},
  	{name: "sevenOfDiamonds", face: "seven", suit: "diamonds"},
  	{name: "sevenOfClubs", face: "seven", suit: "clubs"},
  	{name: "sevenOfHearts", face: "seven", suit: "hearts"},
  	{name: "eightOfSpades", face: "eight", suit: "spades"},
  	{name: "eightOfDiamonds", face: "eight", suit: "diamonds"},
  	{name: "eightOfClubs", face: "eight", suit: "clubs"},
  	{name: "eightOfHearts", face: "eight", suit: "hearts"},
  	{name: "nineOfSpades", face: "nine", suit: "spades"},
  	{name: "nineOfDiamonds", face: "nine", suit: "diamonds"},
  	{name: "nineOfClubs", face: "nine", suit: "clubs"},
  	{name: "nineOfHearts", face: "nine", suit: "hearts"},
  	{name: "tenOfSpades", face: "ten", suit: "spades",},
  	{name: "tenOfDiamonds", face: "ten", suit: "diamonds", value: 10},
  	{name: "tenOfClubs", face: "ten", suit: "clubs", value: 10},
  	{name: "tenOfHearts", face: "ten", suit: "hearts", value: 10},
  	{name: "jackOfSpades", face: "jack", suit: "spades", value: 10},
  	{name: "jackOfDiamonds", face: "jack", suit: "diamonds", value: 10},
  	{name: "jackOfClubs", face: "jack", suit: "clubs", value: 10},
  	{name: "jackOfHearts", face: "jack", suit: "hearts", value: 10},
  	{name: "queenOfSpades", face: "queen", suit: "spades", value: 10},
  	{name: "queenOfDiamonds", face: "queen", suit: "diamonds", value: 10},
  	{name: "queenOfClubs", face: "queen", suit: "clubs", value: 10},
  	{name: "queenOfHearts", face: "queen", suit: "hearts", value: 10},
  	{name: "kingOfSpades", face: "king", suit: "spades", value: 10},
  	{name: "kingOfDiamonds", face: "king", suit: "diamonds", value: 10},
  	{name: "kingOfClubs", face: "king", suit: "clubs", value: 10},
  	{name: "kingOfHearts", face: "king", suit: "hearts", value: 10}
  ]
end
